plugins {
    id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
    id 'maven-publish'
}

base {
    archivesName = "$rootProject.archives_name-fabric"
}

sourceSets.main {
    java.srcDir rootProject.file('common/src/main/java')
    resources.srcDir rootProject.file('common/src/main/resources')
}

loom {
    mods {
        obs_overlay {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:$rootProject.minecraft_version"
    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    implementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"

    implementation("me.shedaniel.cloth:cloth-config-fabric:$rootProject.cloth_config_version") {
        exclude group: 'net.fabricmc.fabric-api'
    }

    compileOnly "maven.modrinth:modmenu:$rootProject.modmenu_version"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
