# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 2.1.0
maven_group = me.zziger.obsoverlay
archives_name = obs_overlay

# Minecraft properties
minecraft_version = 26.2
supported_version = 26.2

# Dependencies
fabric_loader_version = 0.19.3
fabric_api_version = 0.154.2+26.2
neoforge_version = 26.2.0.12-beta
cloth_config_version = 26.2.155
modmenu_version = 20.0.1
curseforge_id = 1067729
modrinth_id = yi1wtIHz
