# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 2.2.0
maven_group = me.zziger.obsoverlay
archives_name = obs_overlay

# Minecraft properties
minecraft_version = 26.3
supported_version = 26.3

# Dependencies
fabric_loader_version = 0.19.5
fabric_api_version = 0.161.0+26.3
neoforge_version = 26.3.0.48-beta
cloth_config_version = 26.3.159
modmenu_version = 21.0.0
curseforge_id = 1067729
modrinth_id = yi1wtIHz
