file(WRITE "${SHADER_DIR}/hud_shaders.hpp" "// Generated from the original MIT-licensed HUD shaders.\n#pragma once\n#include <cstdint>\nnamespace obsvk_shaders {\n")
foreach(stage IN ITEMS vert frag)
    file(READ "${SHADER_DIR}/hud.${stage}.spv" hex HEX)
    string(LENGTH "${hex}" length)
    math(EXPR last "${length} - 8")
    file(APPEND "${SHADER_DIR}/hud_shaders.hpp" "inline constexpr uint32_t ${stage}[] = {\n")
    foreach(offset RANGE 0 ${last} 8)
        string(SUBSTRING "${hex}" ${offset} 8 word)
        string(SUBSTRING "${word}" 0 2 a)
        string(SUBSTRING "${word}" 2 2 b)
        string(SUBSTRING "${word}" 4 2 c)
        string(SUBSTRING "${word}" 6 2 d)
        file(APPEND "${SHADER_DIR}/hud_shaders.hpp" "0x${d}${c}${b}${a}u,\n")
    endforeach()
    file(APPEND "${SHADER_DIR}/hud_shaders.hpp" "};\n")
endforeach()
file(APPEND "${SHADER_DIR}/hud_shaders.hpp" "}\n")
