plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}

base {
    archivesName = "$rootProject.archives_name-neoforge"
}

sourceSets.main {
    java.srcDir rootProject.file('common/src/main/java')
    resources.srcDir rootProject.file('common/src/main/resources')
}

neoForge {
    version = rootProject.neoforge_version

    runs {
        client {
            client()
            gameDirectory = project.file('run')
        }
    }

    mods {
        obs_overlay {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation "me.shedaniel.cloth:cloth-config-neoforge:$rootProject.cloth_config_version"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
